export const courseBackgroundImage = {
  'course-concept-card-bg': 'var(--course-concept-card-bg)',
  'course-guided-card-bg': 'var(--course-guided-card-bg)',
  'course-hackathon-card-bg': 'var(--course-hackathon-card-bg)',
  'course-learning-track-card-bg': 'var(--course-learning-track-card-bg)',
  'course-syntax-card-bg': 'var(--course-syntax-card-bg)',
  'course-teaser-card-bg': 'var(--course-teaser-card-bg)'
};

export const courseThemeColors = {
  'course-card-title-text-color': 'var(--course-card-title-text-color)',
  'course-tag-border-color': 'var(--course-tag-border-color)',
  'course-tag-learning-track-border-color': 'var(--course-tag-learning-track-border-color)',
  'course-tag-learning-track-text-color': 'var(--course-tag-learning-track-text-color)',
  'course-card-description-text-color': 'var(--course-card-description-text-color)',
  'course-banner-arrow-bg': 'var(--course-banner-arrow-bg)',
  'course-banner-arrow-color': 'var(--course-banner-arrow-color)',
  'line-color': 'var(--line-color)',
  'course-progress-button-bg': 'var(--course-progress-button-bg)',
  'course-progress-button-icon-bg': 'var(--course-progress-button-icon-color)',
  'course-progress-button-text-bg': 'var(--course-progress-button-text-color)',
  'course-learning-button-bg': 'var(--course-learning-button-bg)',
  'course-learning-button-text-color': 'var(--course-learning-button-text-color)',
  'course-learning-button-border-color': 'var(--course-learning-button-border-color)',
  'course-progress-border-color': 'var(--course-progress-border-color)',
  'course-progress-text-color': 'var(--course-progress-text-color)',
  'course-detail-desc-text-color': 'var(--course-detail-desc-text-color)',
  'course-unit-desc-text-color': 'var(--course-unit-desc-text-color)',
  'course-unit-lock-icon-color': 'var(--course-unit-lock-icon-color)',
  'course-detail-type-text-color': 'var(--course-detail-type-text-color)',
  'course-detail-desc-border-color': 'var(--course-detail-desc-border-color)',
  'course-progress-icon-color': 'var(--course-progress-icon-color)',
  'earning-track-progress-border-color': 'var(--earning-track-progress-border-color)',
  'learning-track-progress-text-color': 'var(--learning-track-progress-text-color)',
  'learning-track-course-hover-bg': 'var(--learning-track-course-hover-bg)',
  'learning-track-course-title-color': 'var(--learning-track-course-title-color)',
  'learning-track-course-type-color': 'var(--learning-track-course-type-color)',
  'course-banner-arrow-hover-bg': 'var(--course-banner-arrow-hover-bg)',
  'course-banner-arrow-border-color': 'var(--course-banner-arrow-border-color)',
  'course-banner-arrow-border-hover-color': 'var(--course-banner-arrow-border-hover-color)',
  'course-banner-arrow-hover-color': 'var(--course-banner-arrow-hover-color)'
};
