export const lessonThemeColors = {
  'lesson-global-bg': 'var(--lesson-global-bg)',
  'lesson-content-global-bg': 'var(--lesson-content-global-bg)',
  'lesson-left-session-bg': 'var(--lesson-left-session-bg)',
  'lesson-left-session-text-color': 'var(--lesson-left-session-text-color)',
  'lesson-right-session-bg': 'var(--lesson-right-session-bg)',
  'lesson-right-session-border-color': 'var(--lesson-right-session-border-color)',
  'lesson-right-session-hover-bg': 'var(--lesson-right-session-hover-bg)',
  'lesson-right-session-text-color': 'var(--lesson-right-session-text-color)',
  'lesson-right-session-hover-text-color': 'var(--lesson-right-session-hover-text-color)',
  'lesson-right-session-hover-border-color': 'var(--lesson-right-session-hover-border-color)',
  'lesson-dropdown-text-color': 'var(--lesson-dropdown-text-color)',
  'lesson-dropdown-border-color': 'var(--lesson-dropdown-border-color)',
  'lesson-dropdown-select-text-color': 'var(--lesson-dropdown-select-text-color)',
  'lesson-dropdown-select-bg': 'var(--lesson-dropdown-select-bg)',
  'lesson-dropdown-disable-text-color': 'var(--lesson-dropdown-disable-text-color)',
  'lesson-dropdown-bg': 'var(--lesson-dropdown-bg)',
  'lesson-primary-button-bg': 'var(--lesson-primary-button-bg)',
  'lesson-primary-button-text-color': 'var(--lesson-primary-button-text-color)',
  'lesson-ghost-button-bg': 'var(--lesson-ghost-button-bg)',
  'lesson-ghost-border-color': 'var(--lesson-ghost-border-color)',
  'lesson-ghost-button-text-color': 'var(--lesson-ghost-button-text-color)',
  'lesson-header-back-button-bg': 'var(--lesson-header-back-button-bg)',
  'lesson-header-back-button-hover-bg': 'var(--lesson-header-back-button-hover-bg)',
  'lesson-header-back-button-border-color': 'var(--lesson-header-back-button-border-color)',
  'lesson-header-back-button-border-hover-color': 'var(--lesson-header-back-button-border-hover-color)',
  'lesson-header-back-icon-color': 'var(--lesson-header-back-icon-color)',
  'lesson-header-back-icon-hover-color': 'var(--lesson-header-back-icon-hover-color)',
  'lesson-dropdown-select-line-color': 'var(--lesson-dropdown-select-line-color)',
  'lesson-dropdown-select-border-color': 'var(--lesson-dropdown-select-border-color)',
  'lesson-dropdown-icon-color': 'var(--lesson-dropdown-icon-color)',
  'lesson-primary-button-border-color': 'var(--lesson-primary-button-border-color)',
  'lesson-completed-modal-bg': 'var(--lesson-completed-modal-bg)',
  'lesson-completed-modal-line-color': 'var(--lesson-completed-modal-line-color)',
  'lesson-code-copy-button-bg': 'var(--lesson-code-copy-button-bg)',
  'lesson-code-copy-button-text': 'var(--lesson-code-copy-button-text)',
  'lesson-code-editor-input-text-color': 'var(--lesson-code-editor-input-text-color)',
  'lesson-code-editor-input-bg': 'var(--lesson-code-editor-input-bg)',
  'lesson-footer-bg': 'var(--neutral-rich-gray)',
  'lesson-preview-color': 'var(--lesson-preview-color)',
  'lesson-events-toggle-list-box-shadow': 'var(--lesson-events-toggle-list-box-shadow)',
  'lesson-code-index': 'var(--lesson-code-index)'
};

export const lessonThemeBackgroundColor = {
  'lesson-footer-tab-bg': 'var(--lesson-footer-tab-bg)',
  'lesson-footer-tab-active-bg': 'var(--lesson-footer-tab-active-bg)',
  'lesson-events-left-border-bg': 'var(--lesson-events-left-border-bg)',
  'lesson-events-toggle-bg': 'var(--lesson-events-toggle-bg)',
  'lesson-events-toggle-list-bg': 'var(--lesson-events-toggle-list-bg)',
  'lesson-events-toggle-list-active-bg': 'var(--lesson-events-toggle-list-active-bg)',
  'lesson-code-bg': 'var(--lesson-code-bg)',
  'lesson-code-input-bg': 'var(--lesson-code-input-bg)',
  'lesson-code-copy-bg': 'var(--lesson-code-copy-bg)'
};
export const lessonThemeBorderColor = {
  'lesson-footer-tab-border': 'var(--lesson-footer-tab-border)',
  'lesson-footer-tab-active-border': 'var(--lesson-footer-tab-active-border)',
  'lesson-title-box-border-color': 'var(--lesson-title-box-border-color)',
  'lesson-code-input-border': 'var(--lesson-code-input-border)'
};
